version: "3.7"

services:
  queue-management-service:
    init: true
    build:
      dockerfile: ./Dockerfile
    image: queue-management-service:latest
    container_name: queue-management-service
    ports:
      - '8080:8080'
    restart: on-failure

networks:
  default:
    name: queue-management-service